# Generated by Django 4.2.6 on 2023-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message_text', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'quiz_contact',
            },
        ),
    ]
