# Generated by Django 4.2.6 on 2023-11-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player_delete_quiz_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user',
        ),
    ]
