# Generated by Django 4.2.6 on 2023-11-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_username_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name',
        ),
    ]
